//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.Controller2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceState
    {
        public int id { get; set; }
        public string DeviceName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> PIN { get; set; }
    }
}
