//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.Controller2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ID { get; set; }
        public string VoiceCommand { get; set; }
        public string CommandUrl { get; set; }
        public string MachineAnswer { get; set; }
        public Nullable<bool> isAction { get; set; }
        public Nullable<bool> isSpeak { get; set; }
        public string SpecialParam { get; set; }
        public Nullable<int> DeviceID { get; set; }
    }
}
